config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  devise_for :users

  resources :diaries
  resources :diary_drugs
  resources :drugs
  resources :prescriptions do
    member do
      post 'add_drug/:drug_id', :action => 'add_drug', :as => 'add_drug'
      delete 'remove_drug/:drug_id', :action => 'remove_drug', :as => 'remove_drug'
    end
  end


  root 'dashboard#show'
end

app/models/drug.rb
class Drug < ApplicationRecord
  validates :brand, presence: true
  validates :name, presence: true
  validates :dose, presence: true

  # associations
  belongs_to :user
  # belongs_to :prescription
  has_and_belongs_to_many :prescriptions,  dependent: :destroy
  has_many :diary_drugs, dependent: :destroy
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_drug, only: [:edit, :update, :destroy]

  def new
    @drug = current_user.drugs.build
  end

  def create
    @drug = current_user.drugs.build(drug_params)
    if @drug.save
      flash[:success] = 'Medication created successfully'
      redirect_to drugs_path
    else
      flash.now[:alert] = 'Medication not created'
      render :new
    end
  end

  def index
    @drugs = current_user.drugs
  end

  def edit
  end

  def update
    if @drug.update(drug_params)
      flash[:success] = 'Medication updated successfully'
      redirect_to drugs_path
    else
      flash.now[:alert] = 'Medication not updated'
      render :new
    end
  end

  def destroy
    if @drug.destroy
      flash[:success] = 'Medication deleted'
      redirect_to drugs_path
    else
      flash.now[:alert] = 'Something went wrong while trying to delete medication'
      render :edit
    end
  end

  private

  def set_drug
    @drug = current_user.drugs.find(params[:id])
  end

  def drug_params
    params.require(:drug).permit(:brand, :name, :dose)
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= simple_form_for([prescription, drug]) do |f| %>
  <%= f.input :brand %>
  <%= f.input :name %>
  <%= f.input :dose %>
  <%= f.button :submit %>
<% end %>

app/views/drugs/edit.html.erb
<div class="page-header">
  <h1>Edit Drug</h1>
  <ul class="actions">
    <li><%= link_to "Delete Medication",
      drug_path(@drug),
      method: :delete,
      data: { confirm: "This will delete the medication and any diary entries associated with it. Are you sure?" },
      class: "btn btn-danger" %></li>
  </ul>
</div>

<%= render 'form', prescription: @prescription, drug: @drug %>

app/views/drugs/index.html.erb
<div class="row header">
  <div class="col-md-9">
    <h1>Medications</h1>
  </div>
  <div class="col-md-3">
    <h1><%= link_to "New Medication", new_drug_path, class: "btn btn-success" %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">Name</div>
  <div class="col-md-3">Brand</div>
  <div class="col-md-3">Dose</div>
  <div class="col-md-3">Actions</div>
</div>

<% @drugs.each do |drug| %>
  <div class="row">
    <!-- <div class="col-md-3"><%#= link_to drug.name, drug %></div> -->
    <div class="col-md-3"><%= drug.name %></div>
    <div class="col-md-3"><%= drug.brand %></div>
    <div class="col-md-3"><%= drug.dose %></div>
    <div class="col-md-3"><%= link_to "Edit", edit_drug_path(drug), class: "btn btn-primary" %></div>
  </div>
<% end %>

app/views/drugs/new.html.erb
<div class="page-header">
  <h1>New Drug</h1>
</div>

<%= render 'form', prescription: @prescription, drug: @drug %>