config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  devise_for :users

  resources :diaries
  resources :diary_drugs
  resources :drugs
  resources :prescriptions do
    member do
      post 'add_drug/:drug_id', :action => 'add_drug', :as => 'add_drug'
      delete 'remove_drug/:drug_id', :action => 'remove_drug', :as => 'remove_drug'
    end
  end


  root 'dashboard#show'
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  validates :clinic, presence: true

  # associations
  belongs_to :user
  # has_and_belongs_to_many :diaries
  # belongs_to :diary
  # has_many :drugs
  has_and_belongs_to_many :drugs,  dependent: :destroy
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prescription, only: [:show, :edit, :update, :destroy, :add_drug, :remove_drug]
  before_action :set_drug, only: [:add_drug, :remove_drug]

  def index
    @prescriptions = current_user.prescriptions
  end

  def new
    @prescription = current_user.prescriptions.build
  end

  def create
    @prescription = current_user.prescriptions.build(prescription_params)
    if @prescription.save
      flash[:success] = 'Prescription created successfully'
      redirect_to @prescription
    else
      flash.now[:alert] = 'Prescription not created'
      render :new
    end
  end

  def show
    @prescription_drugs = @prescription.drugs
    @all_drugs = current_user.drugs
    @available_drugs = @all_drugs - @prescription_drugs
  end

  def edit
  end

  def update
    if @prescription.update(prescription_params)
      flash[:success] = 'Prescription updated successfully'
      redirect_to @prescription
    else
      flash.now[:alert] = 'Prescription not updated'
      render :new
    end
  end

  def destroy
    if @prescription.destroy
      flash[:success] = 'Prescription deleted'
      redirect_to prescriptions_path
    else
      flash.now[:alert] = 'Something went wrong while trying to delete prescription'
      render :edit
    end
  end

  def add_drug
    @prescription.drugs << @drug
    respond_to do |format|
      format.js {}
    end
  end

  def remove_drug
    @prescription.drugs.delete( @drug )
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_prescription
    @prescription = current_user.prescriptions.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:alert] = 'The prescription you were looking for could not be found'
    redirect_to prescriptions_path
  end

  def set_drug
    @drug = current_user.drugs.find(params[:drug_id])
  end

  def prescription_params
    params.require(:prescription).permit(:clinic, :date)
  end

end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_available_drug.html.erb
<div class="row row-striped" id="available-<%= drug.id %>">
  <div class="col-md-3"><%= drug.brand %></div>
  <div class="col-md-3"><%= drug.name %></div>
  <div class="col-md-3"><%= drug.dose %></div>
  <div class="col-md-3">
    <%= link_to 'Add to prescription',
        add_drug_prescription_path(@prescription, drug),
        remote: true,
        method: :post,
        class: "btn btn-primary" %>
  </div>
</div>

app/views/prescriptions/_drug_table_header.html.erb
<div class="row medication-table-header">
  <div class="col-md-3"><h5>Brand</h5></div>
  <div class="col-md-3"><h5>Name</h5></div>
  <div class="col-md-3"><h5>Dose</h5></div>
  <div class="col-md-3"><h5>Actions</h5></div>
</div>

app/views/prescriptions/_form.html.erb
<%= simple_form_for(prescription) do |f| %>
  <%= f.input :clinic %>
  <%= f.input :date, as: :date, as: :string, input_html: {type: :date} %>
  <%= f.button :submit %>
<% end %>

app/views/prescriptions/_prescription_drug.html.erb
<div class="row row-striped" id="prescription-<%= drug.id %>">
  <div class="col-md-3"><%= drug.brand %></div>
  <div class="col-md-3"><%= drug.name %></div>
  <div class="col-md-3"><%= drug.dose %></div>
  <div class="col-md-3">
    <%= link_to 'Remove from prescription',
        remove_drug_prescription_path(@prescription, drug),
        remote: true,
        method: :delete,
        class: 'btn btn-danger' %>
  </div>
</div>

app/views/prescriptions/add_drug.js.erb
// $("#available-<%= @drug.id %>").hide();
// $("#medication-available-table-body").remove("div#available-<%= @drug.id %>");
$("div#available-<%= @drug.id %>").remove();
$("#medication-prescription-table-body").append("<%= escape_javascript(render partial: 'prescription_drug', locals: {drug: @drug}) %>");

app/views/prescriptions/edit.html.erb
<div class="page-header">
  <h1>Edit Prescription</h1>

  <ul class="actions">
    <li><%= link_to "Delete Prescription",
      prescription_path(@prescription),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this prescription?" },
      class: "btn btn-danger" %>
    </li>
  </ul>
</div>

<%= render 'form', prescription: @prescription %>

app/views/prescriptions/index.html.erb
<div class="row header">
  <div class="col-md-9">
    <h1>Prescriptions</h1>
  </div>
  <div class="col-md-3">
    <h1><%= link_to "New Prescription", new_prescription_path, class: "btn btn-success" %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">Clinic</div>
  <div class="col-md-3">Date</div>
  <div class="col-md-3">Created</div>
  <div class="col-md-3">Actions</div>
</div>

<% @prescriptions.each do |prescription| %>
  <div class="row">
    <div class="col-md-3"><%= link_to prescription.clinic, prescription %></div>
    <div class="col-md-3"><%= prescription.date %></div>
    <div class="col-md-3">
      <%= prescription.user.email %><br>
      <%= time_ago_in_words(prescription.created_at) %> ago
    </div>
    <div class="col-md-3">
      <%= link_to "Edit", edit_prescription_path(prescription), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/prescriptions/new.html.erb
<div class="page-header">
  <h1>New Prescription</h1>
</div>

<%= render 'form', prescription: @prescription %>

app/views/prescriptions/remove_drug.js.erb
$("div#prescription-<%= @drug.id %>").remove();
$("#medication-available-table-body").append("<%= escape_javascript(render partial: 'available_drug', locals: {drug: @drug}) %>");

app/views/prescriptions/show.html.erb
<div class="row header">
  <div class="col-md-9">
    <h1>Prescription - <%= @prescription.clinic %></h1>
  </div>
  <div class="col-md-3">
    <h1><%= link_to "New Medication", new_drug_path, class: "btn btn-success" %></h1>
  </div>
</div>

<!-- <div class="page-header">
  <h1>Prescription - <%= @prescription.clinic %></h1>
  <%= link_to "New Medication", new_drug_path, class: "btn btn-primary pull-right" %> -->

  <!-- <ul class="actions">
    <li><%= link_to "Edit",
      edit_prescription_path(@prescription), class: "btn btn-primary" %></li>
    <li><%= link_to "Delete Prescription",
      prescription_path(@prescription),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this prescription?" },
      class: "btn btn-danger" %></li>
  </ul> -->
<!-- </div> -->

<div class="page-header">
  <h3>Prescription's medications</h3>
</div>

<%= render 'drug_table_header' %>

<%# if @prescription_drugs.empty? %>
  <!-- No medication added to this prescription yet -->
<%# else %>
<div id="medication-prescription-table-body">
  <% @prescription_drugs.each do |drug| %>
    <%= render partial: 'prescription_drug', locals: {drug: drug} %>
  <% end %>
</div>
<%# end %>

<div class="row">
  <div class="col-md-9">
  <!-- <div class="page-header"> -->
    <h3>Available medications</h3>
  </div>
  <!-- <div class="col-md-3">
    <h3><%#= link_to "New Medication", new_drug_path, class: "btn btn-primary" %></h3>
  </div> -->
</div>

<%= render 'drug_table_header' %>

<%#if @available_drugs.empty? %>
  <!-- No medications availble -->
<%# else %>
<div id="medication-available-table-body">
  <% @available_drugs.each do |drug| %>
    <%= render partial: 'available_drug', locals: {drug: drug} %>
  <% end %>
</div>
<%# end %>

app/views/prescriptions/show_OLD_TABLE.html.erb
<div class="page-header">
  <h1>Prescription - <%= @prescription.clinic %></h1>

  <ul class="actions">
    <li><%= link_to "Edit",
      edit_prescription_path(@prescription), class: "btn btn-primary" %></li>
    <li><%= link_to "Delete Prescription",
      prescription_path(@prescription),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this prescription?" },
      class: "btn btn-danger" %></li>
  </ul>
</div>

<div class="page-header">
  <h3>Prescription Medication</h3>

  <!-- <ul class="actions">
    <li><%#= link_to "New Medication",
      new_prescription_drug_path(@prescription), class: "btn btn-primary" %></li>
  </ul> -->
</div>

<table id="medication-prescription-table" class="table">
  <thead>
   <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Dose</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @prescription_drugs.empty? %>
      <tr><td colspan="4">No medication added to this prescription yet</td></tr>
    <% else %>
      <% @prescription_drugs.each do |drug| %>
        <tr>
          <td><%= drug.brand %></td>
          <td><%= drug.name %></td>
          <td><%= drug.dose %></td>
          <td><%= link_to 'Remove from prescription',
          remove_drug_prescription_path(@prescription, drug),
          method: :delete,
          class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="page-header">
  <h3>Available Medication</h3>

  <ul class="actions">
    <li><%= link_to "New Medication",
      new_drug_path, class: "btn btn-primary" %></li>
  </ul>
</div>

<table id="medication-prescription-table" class="table">
  <thead>
   <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Dose</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @available_drugs %>
      <% @available_drugs.each do |drug| %>
        <tr>
          <td><%= drug.brand %></td>
          <td><%= drug.name %></td>
          <td><%= drug.dose %></td>
          <td>
            <%= link_to 'Add to prescription',
                add_drug_prescription_path(@prescription, drug),
                method: :post,
                class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan="4">No medication created for this prescription yet</td></tr>
    <% end %>
  </tbody>
</table>