config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  devise_for :users

  resources :diaries
  resources :diary_drugs
  resources :drugs
  resources :prescriptions do
    member do
      post 'add_drug/:drug_id', :action => 'add_drug', :as => 'add_drug'
      delete 'remove_drug/:drug_id', :action => 'remove_drug', :as => 'remove_drug'
    end
  end


  root 'dashboard#show'
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :title, presence: true

  # associations
  belongs_to :user
  # has_and_belongs_to_many :prescriptions
  # has_many :entries
  has_one :prescription
  has_many :diary_drugs, dependent: :destroy
  # has_many :drugs, through: :diary_drugs
end

app/models/drug.rb
class Drug < ApplicationRecord
  validates :brand, presence: true
  validates :name, presence: true
  validates :dose, presence: true

  # associations
  belongs_to :user
  # belongs_to :prescription
  has_and_belongs_to_many :prescriptions,  dependent: :destroy
  has_many :diary_drugs, dependent: :destroy
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :set_prescription, only: [:show]

  def new
    @diary = current_user.diaries.build
    @prescriptions = current_user.prescriptions
  end

  def create
    @diary = current_user.diaries.build(title: diary_params[:title], description: diary_params[:description])
    @prescription = current_user.prescriptions.where(id: diary_params[:prescription]).first
    if @diary.save
      @diary.prescription = @prescription if @prescription
      flash[:success] = 'Diary created successfully'
      redirect_to @diary
    else
      flash.now[:alert] = 'Diary was not created'
      # FIXME - this query is just to get the tests to pass:
      @prescriptions = current_user.prescriptions
      render :new
    end
  end

  def show
    set_todays_date
    if @prescription
      @drugs = @prescription.drugs
      @entries = []
      @drugs.each do |drug|
        @entries << DiaryDrug.find_or_initialize_by(diary: @diary, drug: drug, date: @today.to_s(:db))
      end
    end
  end

  def index
    @diaries = current_user.diaries.all
  end

  def edit
    @prescriptions = current_user.prescriptions
  end

  def update
    @prescription = current_user.prescriptions.where(id: diary_params[:prescription]).first
    if @diary.update(title: diary_params[:title], description: diary_params[:description])
      @diary.prescription = @prescription if @prescription
      flash[:success] = 'Diary updated successfully'
      redirect_to @diary
    else
      flash.now[:alert] = 'Diary was not updated'
      # FIXME - this query is just to get the tests to pass:
      @prescriptions = current_user.prescriptions
      render :edit
    end
  end

  def destroy
    if @diary.destroy
      flash[:success] = "Diary successfully deleted"
      redirect_to diaries_path
    else
      flash[:alert] = "Diary not deleted"
      redirect_to @diary
    end
  end

  private

  def set_diary
    @diary = current_user.diaries.find(params[:id])
    session[:diary_id] = @diary.id
  rescue ActiveRecord::RecordNotFound => e
    flash[:alert] = 'The diary you were looking for could not be found'
    redirect_to diaries_path
  end

  def set_prescription
    @prescription = @diary.prescription
  end

  def set_todays_date
    if params[:date].nil?
      @today = Date.today
    else
      @today = Date.parse(params[:date])
    end
    session[:date] = @today
  end

  def diary_params
    params.require(:diary).permit(:title, :description, :prescription)
  end

end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_form.html.erb
<%= simple_form_for(diary) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%#= f.association :prescriptions, label_method: :clinic, value_method: :id, include_blank: false, multiple: false, prompt: "Choose a Prescription" %>
  <%= f.label :prescription_id %>
  <%#= f.collection_select(:prescription_ids, @prescriptions, :id, :clinic) %>
  <%= f.collection_select(:prescription, @prescriptions, :id, :clinic) %><br>
  <%= f.button :submit %>
<% end %>

app/views/diaries/_prev_today_next.html.erb
<div class="col-md-5">
  <%= link_to diary_path(@diary, {date: @today.yesterday }) do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
    <span class="hidden-sm-down"> Previous Day</span>
  <% end %>
</div>
<div class="col-md-2">
  <span class="text-center"><%= @today.strftime("%B %-d, %Y") %></span>
</div>
<div class="col-md-5">
  <%= link_to diary_path(@diary, {date: @today.tomorrow }) do %>
    <span class="pull-right">
      <span class="hidden-sm-down"> Next Day</span>
      <i class="fa fa-arrow-right" aria-hidden="true"></i>
    </span>
  <% end %>
</div>

app/views/diaries/edit.html.erb
<div class="page-header">
  <h1>Edit Diary</h1>

  <ul class="actions">
    <li><%= link_to "Delete Diary",
      diary_path(@diary),
      method: :delete,
      data: { confirm: "This will delete the diary and remove all entries. Are you sure?" },
      class: "btn btn-danger" %></li>
  </ul>
</div>

<%= render 'form', {diary: @diary} %>

app/views/diaries/index.html.erb
<div class="row header">
  <div class="col-md-9">
    <h1>Diaries</h1>
  </div>
  <div class="col-md-3">
    <h1><%= link_to "New Diary", new_diary_path, class: "btn btn-success" %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-3">Title</div>
  <div class="col-md-3">Description</div>
  <div class="col-md-3">Prescription</div>
  <div class="col-md-3">Actions</div>
</div>

<% @diaries.each do |diary| %>
  <div class="row">
    <div class="col-md-3"><%= link_to diary.title, diary %></div>
    <div class="col-md-3"><%= diary.description %></div>
    <div class="col-md-3">
      <% if diary.prescription %>
        <%= link_to diary.prescription.clinic, diary.prescription %>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= link_to "Edit", edit_diary_path(diary), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/diaries/new.html.erb
<div class="page-header">
  <h1>New Diary</h1>
</div>

<%= render 'form', diary: @diary %>

app/views/diaries/show.html.erb
<div class="row header">
  <div class="col-md-12">
    <h1><%= @diary.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'prev_today_next' %>
  </div>
</div>

<!-- FIXME - clean up these messages -->
<% if @prescription.nil?  %>
  <div class="row">
    <div class="col-md-12">
      <p>No Prescription associated with this diary.</p>
      <p>Would you like to <%= link_to 'Choose Prescription', prescriptions_path %> or <%= link_to 'Create Prescription', new_prescription_path %></p>
    </div>
  </div>
<% elsif @entries && @entries.empty? %>
  <div class="row">
    <div class="col-md-12">
      <p>No medication has been added to the prescription.</p>
      <p>You can add medication to it <%= link_to 'here', @prescription %> or you can <%= link_to 'Create New Prescription', new_prescription_path %></p>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2"><h5>Brand</h5></div>
      <div class="col-md-2"><h5>Name</h5></div>
      <div class="col-md-1"><h5>Dose</h5></div>
      <div class="col-md-3"><h5>Result</h5></div>
      <div class="col-md-3"><h5>Comments</h5></div>
      <div class="col-md-1"><h5>Actions</h5></div>
    </div>
  </div>

  <% @entries.each do |entry| %>
    <div class="row row-striped">
      <div class="col-md-12">
        <div id="drug-form-<%= entry.drug_id %>">
          <%= render partial: 'diary_drugs/form', locals: {diary_drug: entry} %>
        </div>
      </div>
    </div>
  <% end %>

<% end %>